title: Acid Gospels
#description: 
author: Saransh Karira
#github: https://github.com/saranshkarira
#about: Red Line, Black Thorns
#disqus_shortname: stackproblems
#google_analytics: UA-XXXXXXXX-Y
encoding: utf-8
enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
        #    - icon: fa-facebook
        #      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/saransh_karira"
      #    - icon: fa-linkedin
      #      link: "#"
      #    - icon: fa-stack-exchange
      #      link: "#"
      #    - icon: fa-github
      #      link: "https://github.com/saranshkarira"

share:
  twitter_username: saransh_karira
  #fb_appid: 1749788565247320

urls:
        #    - text: About 
        #      url: /about/
      #    - text: My Projects
      #      url: /projects/
      #    - text: XML Feed
      #      url: /feed.xml

url: "saran.sh"
baseurl: ""
future: true
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
